/*-----------------------------------------------------------------------------
  File:   sip.h
  Description: General SIP header file, according to RFC 3261
  Author: Olof Hagsand
  CVS Version: $Id: sip.h,v 1.4 2005/01/12 18:13:03 olof Exp $
 
  This software is a part of SICSOPHONE, a real-time, IP-based system for 
  point-to-point delivery of audio between computer end-systems.  

  Sicsophone is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  Sicsophone is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Sicsophone; see the file COPYING.

 *---------------------------------------------------------------------------*/
#ifndef _SIP_H_
#define _SIP_H_

#ifdef HAVE_CONFIG_H
#include "config.h" /* generated by config & autoconf */
#endif

/*
 * Constants
 */
#define SIP_VERSION "SIP/2.0"
#define SIP_PORT     5060     /* SIP port */
#define SIP_FLEN     64       /* Default string length */
#define URI_LEN      64       /* MAX sip URI length */
#define DISP_LEN     32       /* MAX sip display length */
#define TAG_LEN      32       /* MAX sip tag length */
#define BRANCH_LEN   64       /* MAX sip branch length */
#define BRANCH_MAGIC "z9hG4bK" /* Branch prefix magic cookie */

/*
 * Types
 */

/*
 * Includes
 */
/* Circular dependency means we have to forward some structs */
struct sip_msg;               /* sip_msg.h */
struct sip_client;            /* sip_client.h */
struct sip_dialog;            /* sip_dialog.h */
struct sip_transaction;       /* sip_transaction.h */

#include "sip_msghdr.h"
#include "sip_msg_invite.h"
#include "sip_msg_response.h"
#include "sip_msg.h"
#include "sip_dialog.h"
#include "sip_client.h"
#include "sip_transaction.h"

/*
 * Variables
 */
extern int dbg_sip; /* sip_client.c */

/*
 * Prototypes
 */ 

#endif  /* _SIP_H_ */


