/*-----------------------------------------------------------------------------
  File:   sphone_win32.c
  Description: Windoze support functions
  Author: Olof Hagsand
  CVS Version: $Id: sphone_win32.c,v 1.1 2005/01/31 18:43:30 olof Exp $
 
  This software is a part of SICSOPHONE, a real-time, IP-based system for 
  point-to-point delivery of audio between computer end-systems.  

  Sicsophone is free software; you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation; either version 2 of the License, or
  (at your option) any later version.

  Sicsophone is distributed in the hope that it will be useful,
  but WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
  GNU General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with Sicsophone; see the file COPYING.

 *---------------------------------------------------------------------------*/
#ifdef HAVE_CONFIG_H
#include "config.h" /* generated by config & autoconf */
#endif

#include <stdio.h>

#ifdef WIN32
#include "sphone.h"

#include <windows.h>
#include <process.h>
#include <mmsystem.h>

#include "sphone_win32.h"

/*
 * thanx to Yuri
 */
LRESULT CALLBACK 
WndMainProc (HWND hWnd, UINT message, WPARAM wParam, LPARAM lParam)
{ // WndMainProc //

  dbg_print(DBG_APP, "WndMainProc %d\n", message);
  switch(message)

    { // Window msgs handling

    case WM_MENUCHAR:
      return (MNC_IGNORE<<16);

    case WM_CHAR:
    case WM_SYSCHAR:
    case WM_SYSCOMMAND:
      //    case WM_DESTROY:
    case WM_CLOSE:
      break;

      //          case WM_GRAPHNOTIFY:
      //      break;
		
         case WM_DESTROY:
            PostQuitMessage(0);
            break;

    default:
      return DefWindowProc(hWnd, message, wParam, lParam);

    } // Window msgs handling

  return FALSE;

} // WndMainProc //

HWND
create_dumb_window(HINSTANCE hInstC)
{
  HWND      ghApp;
  HINSTANCE ghInst;

  WNDCLASS wc;

  // OLE subsystem requires applications to initialize things first!
  CoInitialize(NULL);

  ZeroMemory(&wc, sizeof wc);
  wc.lpfnWndProc = WndMainProc;
  ghInst = wc.hInstance = hInstC;
  wc.hbrBackground = (HBRUSH)GetStockObject(BLACK_BRUSH);
  wc.lpszClassName = "Sicsophone";
  wc.lpszMenuName = MAKEINTRESOURCE(42);
  wc.hCursor = LoadCursor(NULL, IDC_ARROW);
  wc.hIcon = LoadImage(hInstC, MAKEINTRESOURCE(1), IMAGE_ICON, 0 , 0, 0);
  RegisterClass(&wc);

  ghApp = CreateWindow("Sicsophone",
		       "Sicsophone",
		       WS_OVERLAPPEDWINDOW,
		       CW_USEDEFAULT,
		       CW_USEDEFAULT,
		       CW_USEDEFAULT,
		       CW_USEDEFAULT,
		       0,
		       0,
		       ghInst,
		       0);
  //  ghMenu = GetMenu(ghApp);

  //  ShowWindow(ghApp, SW_SHOWNORMAL);
  // UpdateWindow(ghApp);

  return ghApp;
}
#endif /* WIN32 */
